// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_received  Status = 0
	Status_applied   Status = 1
	Status_error     Status = 2
	Status_discarded Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "received",
		1: "applied",
		2: "error",
		3: "discarded",
	}
	Status_value = map[string]int32{
		"received":  0,
		"applied":   1,
		"error":     2,
		"discarded": 3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	NeonpulseIds  []string               `protobuf:"bytes,4,rep,name=neonpulse_ids,json=neonpulseIds,proto3" json:"neonpulse_ids,omitempty"`
	Details       *anypb.Any             `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfig) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceConfig) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ServiceConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceConfig) GetNeonpulseIds() []string {
	if x != nil {
		return x.NeonpulseIds
	}
	return nil
}

func (x *ServiceConfig) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type ModbusConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // copied from parent message since modbus app needs this id to create status file
	NeonpulseId   string                 `protobuf:"bytes,2,opt,name=neonpulse_id,json=neonpulseId,proto3" json:"neonpulse_id,omitempty"`       // copied from parent message since modbus app needs this id to create status file
	Kontext       string                 `protobuf:"bytes,3,opt,name=kontext,proto3" json:"kontext,omitempty"`
	Serials       []*Serial              `protobuf:"bytes,4,rep,name=serials,proto3" json:"serials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModbusConfig) Reset() {
	*x = ModbusConfig{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModbusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModbusConfig) ProtoMessage() {}

func (x *ModbusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModbusConfig.ProtoReflect.Descriptor instead.
func (*ModbusConfig) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ModbusConfig) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ModbusConfig) GetNeonpulseId() string {
	if x != nil {
		return x.NeonpulseId
	}
	return ""
}

func (x *ModbusConfig) GetKontext() string {
	if x != nil {
		return x.Kontext
	}
	return ""
}

func (x *ModbusConfig) GetSerials() []*Serial {
	if x != nil {
		return x.Serials
	}
	return nil
}

type Serial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Baud          int32                  `protobuf:"varint,3,opt,name=baud,proto3" json:"baud,omitempty"`
	DataBits      int32                  `protobuf:"varint,4,opt,name=data_bits,json=dataBits,proto3" json:"data_bits,omitempty"`
	Parity        string                 `protobuf:"bytes,5,opt,name=parity,proto3" json:"parity,omitempty"`
	StopBits      int32                  `protobuf:"varint,6,opt,name=stop_bits,json=stopBits,proto3" json:"stop_bits,omitempty"`
	Slaves        []*Slave               `protobuf:"bytes,7,rep,name=slaves,proto3" json:"slaves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Serial) Reset() {
	*x = Serial{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Serial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Serial) ProtoMessage() {}

func (x *Serial) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Serial.ProtoReflect.Descriptor instead.
func (*Serial) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Serial) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Serial) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Serial) GetBaud() int32 {
	if x != nil {
		return x.Baud
	}
	return 0
}

func (x *Serial) GetDataBits() int32 {
	if x != nil {
		return x.DataBits
	}
	return 0
}

func (x *Serial) GetParity() string {
	if x != nil {
		return x.Parity
	}
	return ""
}

func (x *Serial) GetStopBits() int32 {
	if x != nil {
		return x.StopBits
	}
	return 0
}

func (x *Serial) GetSlaves() []*Slave {
	if x != nil {
		return x.Slaves
	}
	return nil
}

type Slave struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Address                  int32                  `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                     int32                  `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
	FwVersion                string                 `protobuf:"bytes,3,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	Type                     string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                        // DSL to use
	HardwareMaker            string                 `protobuf:"bytes,5,opt,name=hardware_maker,json=hardwareMaker,proto3" json:"hardware_maker,omitempty"` // defaults to ""
	HardwareModel            string                 `protobuf:"bytes,6,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"` // defaults to ""
	SpannungsebeneTeilanlage string                 `protobuf:"bytes,7,opt,name=spannungsebene_teilanlage,json=spannungsebeneTeilanlage,proto3" json:"spannungsebene_teilanlage,omitempty"`
	Rebirth                  bool                   `protobuf:"varint,8,opt,name=rebirth,proto3" json:"rebirth,omitempty"`
	ScanRate                 int32                  `protobuf:"varint,9,opt,name=scan_rate,json=scanRate,proto3" json:"scan_rate,omitempty"`
	Leittechnikkomponente    int32                  `protobuf:"varint,10,opt,name=leittechnikkomponente,proto3" json:"leittechnikkomponente,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Slave) Reset() {
	*x = Slave{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slave) ProtoMessage() {}

func (x *Slave) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slave.ProtoReflect.Descriptor instead.
func (*Slave) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Slave) GetAddress() int32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Slave) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Slave) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *Slave) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Slave) GetHardwareMaker() string {
	if x != nil {
		return x.HardwareMaker
	}
	return ""
}

func (x *Slave) GetHardwareModel() string {
	if x != nil {
		return x.HardwareModel
	}
	return ""
}

func (x *Slave) GetSpannungsebeneTeilanlage() string {
	if x != nil {
		return x.SpannungsebeneTeilanlage
	}
	return ""
}

func (x *Slave) GetRebirth() bool {
	if x != nil {
		return x.Rebirth
	}
	return false
}

func (x *Slave) GetScanRate() int32 {
	if x != nil {
		return x.ScanRate
	}
	return 0
}

func (x *Slave) GetLeittechnikkomponente() int32 {
	if x != nil {
		return x.Leittechnikkomponente
	}
	return 0
}

type Confirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	NeonpulseId   string                 `protobuf:"bytes,4,opt,name=neonpulse_id,json=neonpulseId,proto3" json:"neonpulse_id,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=modbus_messages.Status" json:"status,omitempty"`
	Info          string                 `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Confirmation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Confirmation) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Confirmation) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Confirmation) GetNeonpulseId() string {
	if x != nil {
		return x.NeonpulseId
	}
	return ""
}

func (x *Confirmation) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_received
}

func (x *Confirmation) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x0fmodbus_messages\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xe8\x01\n" +
	"\rServiceConfig\x128\n" +
	"\tcreatedAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12#\n" +
	"\rneonpulse_ids\x18\x04 \x03(\tR\fneonpulseIds\x12.\n" +
	"\adetails\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\adetails\"\xa5\x01\n" +
	"\fModbusConfig\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12!\n" +
	"\fneonpulse_id\x18\x02 \x01(\tR\vneonpulseId\x12\x18\n" +
	"\akontext\x18\x03 \x01(\tR\akontext\x121\n" +
	"\aserials\x18\x04 \x03(\v2\x17.modbus_messages.SerialR\aserials\"\xca\x01\n" +
	"\x06Serial\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12\x12\n" +
	"\x04baud\x18\x03 \x01(\x05R\x04baud\x12\x1b\n" +
	"\tdata_bits\x18\x04 \x01(\x05R\bdataBits\x12\x16\n" +
	"\x06parity\x18\x05 \x01(\tR\x06parity\x12\x1b\n" +
	"\tstop_bits\x18\x06 \x01(\x05R\bstopBits\x12.\n" +
	"\x06slaves\x18\a \x03(\v2\x16.modbus_messages.SlaveR\x06slaves\"\xe0\x02\n" +
	"\x05Slave\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\x05R\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\x05R\x04name\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x03 \x01(\tR\tfwVersion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12%\n" +
	"\x0ehardware_maker\x18\x05 \x01(\tR\rhardwareMaker\x12%\n" +
	"\x0ehardware_model\x18\x06 \x01(\tR\rhardwareModel\x12;\n" +
	"\x19spannungsebene_teilanlage\x18\a \x01(\tR\x18spannungsebeneTeilanlage\x12\x18\n" +
	"\arebirth\x18\b \x01(\bR\arebirth\x12\x1b\n" +
	"\tscan_rate\x18\t \x01(\x05R\bscanRate\x124\n" +
	"\x15leittechnikkomponente\x18\n" +
	" \x01(\x05R\x15leittechnikkomponente\"\xfa\x01\n" +
	"\fConfirmation\x128\n" +
	"\tcreatedAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fneonpulse_id\x18\x04 \x01(\tR\vneonpulseId\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.modbus_messages.StatusR\x06status\x12\x12\n" +
	"\x04info\x18\x06 \x01(\tR\x04info*=\n" +
	"\x06Status\x12\f\n" +
	"\breceived\x10\x00\x12\v\n" +
	"\aapplied\x10\x01\x12\t\n" +
	"\x05error\x10\x02\x12\r\n" +
	"\tdiscarded\x10\x03B Z\x1esettingsmanager-ngnix/proto/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messages_proto_goTypes = []any{
	(Status)(0),                   // 0: modbus_messages.Status
	(*ServiceConfig)(nil),         // 1: modbus_messages.ServiceConfig
	(*ModbusConfig)(nil),          // 2: modbus_messages.ModbusConfig
	(*Serial)(nil),                // 3: modbus_messages.Serial
	(*Slave)(nil),                 // 4: modbus_messages.Slave
	(*Confirmation)(nil),          // 5: modbus_messages.Confirmation
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 7: google.protobuf.Any
}
var file_messages_proto_depIdxs = []int32{
	6, // 0: modbus_messages.ServiceConfig.createdAt:type_name -> google.protobuf.Timestamp
	7, // 1: modbus_messages.ServiceConfig.details:type_name -> google.protobuf.Any
	3, // 2: modbus_messages.ModbusConfig.serials:type_name -> modbus_messages.Serial
	4, // 3: modbus_messages.Serial.slaves:type_name -> modbus_messages.Slave
	6, // 4: modbus_messages.Confirmation.createdAt:type_name -> google.protobuf.Timestamp
	0, // 5: modbus_messages.Confirmation.status:type_name -> modbus_messages.Status
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
